server:
  port: 8080
  mode: development

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: your_db_name

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

log:
  level: debug
  filename: ./logs/app.log
  maxsize: 100
  maxage: 7
  maxbackups: 10